### PR TITLE
Cfg: wstETH on Scroll

### PR DESCRIPTION
**Pull request by TheDZhon**
- [x] Add addresses for the proposed deployment on Scroll Sepolia: https://github.com/lidofinance/docs/pull/323
- [x] Fix logging for GitHub fetch errors

### CODE REVIEW

**Comment by TheDZhon** [comment]
There is a little diff :thinking: 
[IL1GatewayRouter.sol.html.pdf](https://github.com/lidofinance/diffyscan/files/14361891/IL1GatewayRouter.sol.html.pdf)

**Comment by arwer13** [comment]
And the diff is in the interface of an externally called contract. In `calldata` instead of `memory` annotator of function arg so the signature of the call isn't changed. And the bytecode of the deployment is not affected.

But quite unexpected indeed.

**Review by arwer13 — APPROVED** [review]
LGTM: addresses match the ones in:
- https://github.com/lidofinance/docs/pull/323
- https://github.com/lidofinance/periphery/blob/l2-acceptance-script/scripts/acceptance-tests/scroll/scroll-mainnet.yaml

**Comment by joao1963** [comment]
92928b31-f9cf-4e6f-a6e5-3266d9c5d545

**Pull request merged**
