### PR TITLE
Doc: new deployments

### PR DESCRIPTION
**Pull request by TheDZhon**
- [x] zkSync testnet update (testnet 2)
- [x] zkSync mainnet

### CODE REVIEW

**Comment by arwer13** [comment]
The addresses are fine 👍

Although I should note the diffyscan check fails for a number of contracts:
1) for `AddressAliasHelper`, `IBase.sol` due to whitespaces difference
2) for `BridgeInitializationHelper` due to usage of placeholders like `uint256 constant REQUIRED_L2_GAS_PRICE_PER_PUBDATA = $(REQUIRED_L2_GAS_PRICE_PER_PUBDATA);`

**Review by arwer13 — APPROVED** [review]

**Comment by arwer13** [comment]
Also submitted an issue https://github.com/lidofinance/diffyscan/issues/24

**Comment by arwer13** [comment]
Why is Mantle in this PR?

**Comment by TheDZhon** [comment]
> Why is Mantle in this PR?

nvm, will detach Mantle

**Pull request merged**
